# Generated by Django 5.0.1 on 2024-01-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='', max_length=20)),
                ('dob', models.DateField(default='')),
                ('photo', models.ImageField(upload_to='images')),
                ('address', models.TextField()),
                ('grades', models.CharField(max_length=2)),
            ],
        ),
    ]
